language: node_js
node_js:
  - "11"
  - "10"
  - "9"
  - "8"
env:
- IOTS=1.6
- IOTS=1.5
- IOTS=1.4
- IOTS=1.3
before_script:
  - yarn add io-ts@"$IOTS"
script:
  - npm run test:coverage
after_success:
  - npm run test:coveralls